project:
  type: website
  output-dir: docs

website:
  title: "Christian Q Raquepo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

